language: node_js
node_js:
  - '10'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - yarn install
  - yarn run build
cache:
  directories:
    - 'node_modules'
before_deploy: echo 'diol.app' > dist/CNAME
notifications:
  email: false
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  github-token: $GITUHB_TOKEN
  repo: diolapp/diolapp.github.io
  keep-history: true
  target-branch: master
  on:
      branch: master